# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(795, 425)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 795, 21))
        self.menubar.setObjectName("menubar")
        self.menuInicio = QtWidgets.QMenu(self.menubar)
        self.menuInicio.setObjectName("menuInicio")
        self.menuHFC = QtWidgets.QMenu(self.menubar)
        self.menuHFC.setObjectName("menuHFC")
        self.menuFibra_Hogar = QtWidgets.QMenu(self.menubar)
        self.menuFibra_Hogar.setObjectName("menuFibra_Hogar")
        MainWindow.setMenuBar(self.menubar)
        self.actionVentana_1 = QtWidgets.QAction(MainWindow)
        self.actionVentana_1.setObjectName("actionVentana_1")
        self.actionVentana_2 = QtWidgets.QAction(MainWindow)
        self.actionVentana_2.setObjectName("actionVentana_2")
        self.actionDTH = QtWidgets.QAction(MainWindow)
        self.actionDTH.setObjectName("actionDTH")
        self.actionHome = QtWidgets.QAction(MainWindow)
        self.actionHome.setObjectName("actionHome")
        self.menuInicio.addAction(self.actionHome)
        self.menuInicio.addAction(self.actionVentana_1)
        self.menuInicio.addAction(self.actionVentana_2)
        self.menuInicio.addAction(self.actionDTH)
        self.menubar.addAction(self.menuInicio.menuAction())
        self.menubar.addAction(self.menuHFC.menuAction())
        self.menubar.addAction(self.menuFibra_Hogar.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuInicio.setTitle(_translate("MainWindow", "Inicio"))
        self.menuHFC.setTitle(_translate("MainWindow", "HFC"))
        self.menuFibra_Hogar.setTitle(_translate("MainWindow", "Fibra Hogar"))
        self.actionVentana_1.setText(_translate("MainWindow", "Fibra Hogar"))
        self.actionVentana_1.setShortcut(_translate("MainWindow", "F"))
        self.actionVentana_2.setText(_translate("MainWindow", "HFC"))
        self.actionVentana_2.setShortcut(_translate("MainWindow", "H"))
        self.actionDTH.setText(_translate("MainWindow", "DTH"))
        self.actionDTH.setShortcut(_translate("MainWindow", "D"))
        self.actionHome.setText(_translate("MainWindow", "Home"))
        self.actionHome.setShortcut(_translate("MainWindow", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
