# -*- coding: utf-8 -*-

# Dialog implementation generated from reading ui file '.\splash.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        # Dialog.setGeometry(QtCore.QRect(438, 209, 490, 350))
        Dialog.resize(498, 356)
        self.widgetWelcolme = QtWidgets.QWidget(Dialog)
        self.widgetWelcolme.setGeometry(QtCore.QRect(0, 0, 490, 350))
        self.widgetWelcolme.setStyleSheet(".QWidget {\n"
"border-radius: 10px;\n"
"background:rgba(255, 255, 255, 220)\n"
"}")
        self.widgetWelcolme.setObjectName("widgetWelcolme")
        self.label = QtWidgets.QLabel(self.widgetWelcolme)
        self.label.setGeometry(QtCore.QRect(100, 10, 261, 121))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/images/icon.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widgetWelcolme)
        self.label_2.setGeometry(QtCore.QRect(20, 130, 441, 101))
        self.label_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(85, 170, 255)")
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.widgetWelcolme)
        self.progressBar.setGeometry(QtCore.QRect(50, 260, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.progressBar.setFont(font)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"border-radius: 10px;\n"
"background-color: rgb(234, 255, 253);\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" color:#55aaff;\">Bienvenidos al asistente de soporte para</span></p><p align=\"center\"><span style=\" color:#55aaff;\">Whatsapp Venezuela</span></p></body></html>"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QWidget()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
